# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DFS <- function(amattt, n_nodes) {
    .Call('_MRSL_DFS', PACKAGE = 'MRSL', amattt, n_nodes)
}

STEP1 <- function(data_sum_beta, data_sum_se, beta1, use_eggers_step1) {
    .Call('_MRSL_STEP1', PACKAGE = 'MRSL', data_sum_beta, data_sum_se, beta1, use_eggers_step1)
}

STEP2 <- function(amattt, data_sum_beta, data_sum_se, beta1, adj_methods, use_eggers_step2, vary_mvmr_adj) {
    .Call('_MRSL_STEP2', PACKAGE = 'MRSL', amattt, data_sum_beta, data_sum_se, beta1, adj_methods, use_eggers_step2, vary_mvmr_adj)
}

